"""Add total_amount_paid and date_registered fields to Employer

Revision ID: 09f1227a7771
Revises: 6c310b46a3e7
Create Date: 2017-11-05 20:18:40.606099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f1227a7771'
down_revision = '6c310b46a3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('date_registered', sa.DateTime(), nullable=True))
    op.add_column('employers', sa.Column('total_amount_paid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'total_amount_paid')
    op.drop_column('employers', 'date_registered')
    # ### end Alembic commands ###
