"""Add amount field to Payment model.

Revision ID: 6c310b46a3e7
Revises: 8580b5c0888c
Create Date: 2017-11-04 04:58:41.117945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c310b46a3e7'
down_revision = '8580b5c0888c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'amount')
    # ### end Alembic commands ###
