"""Add total_salary field to Employee model.

Revision ID: 8c2eb1bfede0
Revises: 09f1227a7771
Create Date: 2017-11-05 23:07:21.111053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2eb1bfede0'
down_revision = '09f1227a7771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('total_salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'total_salary')
    # ### end Alembic commands ###
